services:
  # Backend API Service
  - type: web
    name: ytsbyai-backend
    env: python
    plan: starter
    region: oregon
    buildCommand: |
      pip install -r backend/requirements.txt
    startCommand: |
      cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        sync: false
      - key: NEO4J_PASSWORD
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
      - key: FIREBASE_AUTH_URI
        sync: false
      - key: FIREBASE_TOKEN_URI
        sync: false
      - key: FIREBASE_AUTH_PROVIDER_X509_CERT_URL
        sync: false
      - key: FIREBASE_CLIENT_X509_CERT_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://ytsbyai-frontend.onrender.com,https://ytsbyai.vercel.app
    healthCheckPath: /health
    autoDeploy: false

  # Frontend Web Service
  - type: web
    name: ytsbyai-frontend
    env: node
    plan: starter
    region: oregon
    buildCommand: |
      cd frontend && npm ci && npm run build
    startCommand: |
      cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://ytsbyai-backend.onrender.com
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        sync: false
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        sync: false
    healthCheckPath: /api/health
    autoDeploy: false

databases:
  # Neo4j Database (if using Render's managed Neo4j)
  - name: ytsbyai-neo4j
    databaseName: neo4j
    plan: starter
    region: oregon 